// Working video URLs for demonstration
export const sampleVideos = [
  {
    id: "sample-1",
    title: "Sample Video 1 - Nature Documentary",
    description:
      "Beautiful nature scenes showcasing wildlife and landscapes. Perfect for testing video streaming capabilities.",
    videoUrl: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=225&fit=crop",
    authorId: "nature-channel",
    authorName: "Nature Channel",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
    duration: "0:30",
    category: "Nature",
    tags: ["nature", "documentary", "wildlife"],
    viewCount: 125847,
    likeCount: 3420,
    dislikeCount: 89,
    commentCount: 156,
    createdAt: new Date("2024-01-15").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "sample-2",
    title: "Sample Video 2 - Technology Review",
    description: "Latest technology trends and gadget reviews. Stay updated with the newest tech innovations.",
    videoUrl: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=225&fit=crop",
    authorId: "tech-reviewer",
    authorName: "Tech Reviewer",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    duration: "1:00",
    category: "Technology",
    tags: ["technology", "review", "gadgets"],
    viewCount: 89234,
    likeCount: 2156,
    dislikeCount: 45,
    commentCount: 89,
    createdAt: new Date("2024-01-10").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "sample-3",
    title: "Sample Video 3 - Cooking Tutorial",
    description:
      "Learn to cook delicious meals with step-by-step instructions. Perfect for beginners and experts alike.",
    videoUrl: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=225&fit=crop",
    authorId: "cooking-master",
    authorName: "Cooking Master",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    duration: "0:20",
    category: "Cooking",
    tags: ["cooking", "tutorial", "food"],
    viewCount: 203456,
    likeCount: 5678,
    dislikeCount: 123,
    commentCount: 234,
    createdAt: new Date("2024-01-20").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "sample-4",
    title: "Sample Video 4 - Travel Vlog",
    description:
      "Explore amazing destinations around the world. Join us on this incredible journey through beautiful landscapes.",
    videoUrl: "https://file-examples.com/storage/fe68c1b7c66c4d2b8c5c7a8/2017/10/file_example_MP4_480_1_5MG.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=225&fit=crop",
    authorId: "travel-blogger",
    authorName: "Travel Blogger",
    authorAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    duration: "0:30",
    category: "Travel",
    tags: ["travel", "vlog", "adventure"],
    viewCount: 178923,
    likeCount: 4321,
    dislikeCount: 87,
    commentCount: 198,
    createdAt: new Date("2024-01-18").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "sample-5",
    title: "Sample Video 5 - Music Performance",
    description:
      "Live music performance featuring talented artists. Experience the magic of live music from the comfort of your home.",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop",
    authorId: "music-artist",
    authorName: "Music Artist",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    duration: "9:56",
    category: "Music",
    tags: ["music", "performance", "live"],
    viewCount: 156789,
    likeCount: 4567,
    dislikeCount: 98,
    commentCount: 267,
    createdAt: new Date("2024-01-12").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "sample-6",
    title: "Sample Video 6 - Educational Content",
    description:
      "Learn something new every day with our educational content. Knowledge is power, and we're here to empower you.",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=225&fit=crop",
    authorId: "education-hub",
    authorName: "Education Hub",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
    duration: "10:53",
    category: "Education",
    tags: ["education", "learning", "knowledge"],
    viewCount: 234567,
    likeCount: 6789,
    dislikeCount: 134,
    commentCount: 345,
    createdAt: new Date("2024-01-08").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
]

// Fallback video URLs if the above don't work
export const fallbackVideos = [
  {
    id: "fallback-1",
    title: "Demo Video - Big Buck Bunny",
    description:
      "Classic open source animation by Blender Foundation. A fun and entertaining short film perfect for testing video playback.",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnailUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg",
    authorId: "demo-user",
    authorName: "Demo User",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
    duration: "9:56",
    category: "Animation",
    tags: ["animation", "demo", "entertainment"],
    viewCount: 500000,
    likeCount: 15000,
    dislikeCount: 200,
    commentCount: 1200,
    createdAt: new Date("2024-01-01").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
  {
    id: "fallback-2",
    title: "Demo Video - Elephant Dream",
    description:
      "The world's first open movie made entirely with open source software. A surreal journey through imagination.",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnailUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg",
    authorId: "demo-user",
    authorName: "Demo User",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
    duration: "10:53",
    category: "Animation",
    tags: ["animation", "open source", "creative"],
    viewCount: 350000,
    likeCount: 12000,
    dislikeCount: 150,
    commentCount: 800,
    createdAt: new Date("2024-01-02").toISOString(),
    status: "published" as const,
    visibility: "public" as const,
  },
]

export const sampleComments = [
  {
    id: "comment-1",
    videoId: "sample-1",
    userId: "user-1",
    userName: "Nature Lover",
    userAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    content: "Amazing video quality! The nature scenes are absolutely breathtaking. Thanks for sharing!",
    parentId: undefined,
    likeCount: 24,
    createdAt: new Date("2024-01-16").toISOString(),
    replies: [],
  },
  {
    id: "comment-2",
    videoId: "sample-2",
    userId: "user-2",
    userName: "Tech Enthusiast",
    userAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    content: "Great tech review! Very informative and well presented. Looking forward to more content like this.",
    parentId: undefined,
    likeCount: 18,
    createdAt: new Date("2024-01-11").toISOString(),
    replies: [],
  },
  {
    id: "comment-3",
    videoId: "sample-3",
    userId: "user-3",
    userName: "Food Lover",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    content: "This cooking tutorial is fantastic! Easy to follow and the results are delicious. Thank you!",
    parentId: undefined,
    likeCount: 32,
    createdAt: new Date("2024-01-21").toISOString(),
    replies: [],
  },
]
